### PR TITLE
Create readme.MD

### PR DESCRIPTION
**Pull request by Pen721**

### CODE REVIEW

**Comment by kmeng01** [comment]
nit: grammar

`bro` -> `brother`

**Comment by kmeng01** [comment]
r u chinese or smth

**Comment by kmeng01** [comment]
otherwise LGTM!

**Comment by kmeng01** [comment]
@Aryo-Patel may i have write permission?

**Comment by Aryo-Patel** [comment]
company too broke for this to matter 😭 
+ streamlit only wanted to host on public repos sad

**Pull request merged**
